### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Parukh78** [AIx-Solutions/aix-gpt-api#2]
it seems your API is down at the moment
from the web, it get stucks in a infinite loading loop
<img width="1650" alt="Screenshot 2021-08-02 at 11 23 59" src="https://user-images.githubusercontent.com/88316965/127838075-20650fa2-299d-41ef-ab73-aea17833daa4.png">

**Comment by joshwolff1** [comment]
Hi Parikh78! I am sorry - I am fixing this right now.

**Comment by joshwolff1** [comment]
Hi Parukh78! I just worked for 8 straight hours and fixed it. My apologies! It should work now.
